# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Project_19' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Project_19
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'Firebase/Storage' 
pod 'GoogleSignIn'

  target 'Project_19Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Project_19UITests' do
    # Pods for testing
  end

end
